version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    volumes:
      - redisinsight_data:/db
    ports:
      - "8001:8001"
    restart: unless-stopped

  # identity-service:
  #   build: ../../services/identity-service
  #   command: pnpm dev
  #   volumes:
  #     - ../../services/identity-service:/app
  #   ports:
  #     - "5001:3000"
  #   depends_on:
  #     - postgres

  # event-service:
  #   build: ../../services/event-service
  #   command: pnpm dev
  #   volumes:
  #     - ../../services/event-service:/app
  #   ports:
  #     - "5002:3000"
  #   depends_on:
  #     - postgres

  # comm-service:
  #   build: ../../services/comm-service
  #   command: pnpm dev
  #   volumes:
  #     - ../../services/comm-service:/app
  #   ports:
  #     - "5003:3000"
  #   depends_on:
  #     - postgres



volumes:
  pgdata:
  pgadmin_data:
  redisdata:
  redisinsight_data: